infraApp/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from flask.ext.login import UserMixin
from datetime import datetime
from . import db, login_manager
from markdown import markdown
import bleach

class Projects(db.Model):
    __tablename__ = 'projects'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    prjID = db.Column(db.String(64))
    title = db.Column(db.String(128), nullable=False)
    cost = db.Column(db.Float, nullable=False)
    funding = db.Column(db.String(16))
    contractor = db.Column(db.String(64), nullable=False, index=True)
    address = db.Column(db.Text, nullable=False)
    status = db.Column(db.Float, nullable=False)
    dateStart = db.Column(db.DateTime())
    dateEnd = db.Column(db.DateTime())
    agency = db.Column(db.String(64), nullable=False)
    lat = db.Column(db.Float)
    lon = db.Column(db.Float)
    region = db.Column(db.String(4))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), autoincrement=True)


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), nullable=False, unique=True, index=True)
    is_admin = db.Column(db.Boolean)
    password_hash = db.Column(db.String(128))
    infraProj = db.relationship('Projects', backref='implementor', lazy='dynamic') 

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')
	
    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

class scrapedProjects(db.Model):
    __tablename__ = 'dpwh'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    prjID = db.Column(db.String(64))
    title = db.Column(db.Text)
    contractor = db.Column(db.String(64))
    impOffice = db.Column(db.String(64))
    srcFunds = db.Column(db.String(64))
    cost = db.Column(db.String(64))
    status = db.Column(db.String(64))
    startDate = db.Column(db.String(64))
    origComp = db.Column(db.String(64))
    actComp = db.Column(db.String(64))
    regions = db.Column(db.String(12))
    latitude = db.Column(db.Float)
    longitude = db.Column(db.Float)
    comments= db.relationship('Comment', lazy='dynamic', backref='dpwh')

class Comment(db.Model):
    __tablename__ = "comments"
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    body = db.Column(db.Text)
    body_html = db.Column(db.Text)
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    author_name = db.Column(db.String(64))
    author_email = db.Column(db.String(64))
    approved = db.Column(db.Boolean, default=True)
    prjID = db.Column(db.String(64), db.ForeignKey('dpwh.prjID'))

    @staticmethod
    def on_changed_body(target, value, oldvalue, initiator):
        allowed_tags = [
            'a', 'abbr', 'acronym', 'b', 'blockquote', 'code',
            'em', 'i', 'li', 'ol', 'pre', 'strong', 'ul',
            'h1', 'h2', 'h3', 'p'
        ]
        target.body_html = bleach.linkify(bleach.clean(
                markdown(value, output_format='html'),
                tags=allowed_tags,strip=True
            ))

db.event.listen(Comment.body, 'set', Comment.on_changed_body)

infraApp/infra/forms.py
from flask.ext.wtf import Form
from wtforms import StringField, DateField, TextField, FloatField, SubmitField, SelectField
from wtforms.validators import Required, Length, Optional
from flask.ext.pagedown.fields import PageDownField

class AddProjectForm(Form):

    prjID = StringField('Project ID', validators=[Required(), Length(1,64)])
    title = StringField('Title of Project', validators=[Required(), Length(1,128)])
    cost = 	FloatField('Cost', validators=[Required()])
    contractor = StringField('Contractor', validators=[Required(), Length(1,64)])
    address = TextField('Address of Project', validators=[Required()])
    status = FloatField('% Completed', validators=[Required()])
    dateStart = DateField('Date Start i.e.(YYYY-MM-DD)', validators=[Required()])
    dateEnd = DateField('Date End i.e.(YYYY-MM-DD)', validators=[Required()])
    agency = StringField('Implementing Agency', validators=[Required(), Length(1,64)])
    funding = StringField('Source of Funds', validators=[Required(), Length(1,64)])
    lat = FloatField('Latitude', validators=[Required()],id='latitude')
    lon = FloatField('Longitude', validators=[Required()],id='longitude')
    region = SelectField(u'Region',
            coerce=int,
            choices=[
                (1, '01'),(2, '02'),(3, '03'),(4, '04A'),(5, '04B'),(6, '05'),(7, '06'),
                (8, '07'),(9, '08'),(10, '09'),(11, '10'),(12, '11'),(13, '12'),(13, '12'),
                (14, '13'),(15, 'CAR'),(16, 'NCR')
            ])
    submitData = SubmitField('Submit Project')

class CommentForm(Form):
    name = StringField('Name', validators=[Required(), Length(1,64)])
    email = StringField('Email', validators=[Required(), Length(1,64)])
    body = PageDownField('Comment', validators=[Required()])
    submit = SubmitField('Submit')

class SearchForm(Form):
    title = StringField('', validators=[Required()])
    submit = SubmitField('Go')

class ProjectEditorForm(Form):
    actComp = StringField('Actual Completion', validators=[Required(), Length(1,64)])
    status = FloatField('% Completed')
    lat = FloatField('Latitude:', validators=[Required(), Length(1,64)],id='latitude')
    lng = FloatField('Longitude:', validators=[Required(), Length(1,64)],id='longitude')
    submit = SubmitField('Update')

infraApp/__init__.py
from flask import Flask
from config import config
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.login import LoginManager
from flask.ext.bootstrap import Bootstrap
from flask.ext.pagedown import PageDown

login_manager = LoginManager()
login_manager.login_view = 'auth.login'

db = SQLAlchemy()

bootstrap = Bootstrap()

pagedown=PageDown()

def build_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])

    bootstrap.init_app(app)

    from infraApp.models import db
    db.init_app(app)

    from .infra import infra as infra_blueprint
    app.register_blueprint(infra_blueprint)

    login_manager.init_app(app)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    pagedown.init_app(app)

    return app

infraApp/infra/__init__.py
from flask import Blueprint
infra = Blueprint('infra', __name__)
from . import routes

infraApp/infra/routes.py
from flask import render_template, request, url_for, flash, redirect
from flask.ext.login import login_user, logout_user, login_required
from . import infra
from ..models import User, Projects, scrapedProjects, Comment
from .forms import AddProjectForm, CommentForm, SearchForm, ProjectEditorForm
from .. import db
from api_query import get_list_of_suppliers, get_orginfo_from_orgid, get_orgcategory, get_number_of_previous_bids_of_org, get_awards_total_of_org
import ast

@infra.route('/')
@infra.route('/index')
def index():
    dataList = Projects.query.order_by(Projects.dateStart.desc()).all()
    return render_template('infra/index.html', dataList=dataList)


@infra.route('/addData', methods=['GET', 'POST'])
@login_required
def addProject():
	form = AddProjectForm()
	dataList = Projects.query.order_by(Projects.dateStart.desc()).all()
	if form.validate_on_submit():
		proj = Projects(
				prjID=form.prjID.data,
				title=form.title.data,
				cost=form.cost.data,
				contractor=form.contractor.data,
				address=form.address.data,
				status=form.status.data,
				funding=form.funding.data,
				dateStart=form.dateStart.data,
				dateEnd=form.dateEnd.data,
				agency=form.agency.data,
				lat=form.lat.data,
				lon=form.lon.data,
				region=form.region.data 
			)
		db.session.add(proj)
		db.session.commit()	
		return render_template('infra/index.html', form=form, dataList=dataList)
	return render_template('infra/addData.html', form=form, dataList=dataList)

@infra.route('/projectList', methods=['GET', 'POST'])
def projectList():
	projList = scrapedProjects.query.limit(20)
	form = SearchForm()
	numResults=0
	if form.validate_on_submit():
		projList = scrapedProjects.query.filter(scrapedProjects.title.like('%'+form.title.data+'%'))
		numResults = projList.count()
		return render_template('infra/projects.html', projList=projList, form=form, numResults=numResults)
	return render_template('infra/projects.html', projList=projList, form=form, numResults=numResults)

@infra.route('/project/<prjID>', methods=['GET', 'POST'])
def projectProfile(prjID):
	proj = scrapedProjects.query.filter_by(prjID=prjID).all()
	form = CommentForm()
	comment = None
	if form.validate_on_submit():
		comment=Comment(body=form.body.data, 
			author_name = form.name.data,
			author_email = form.email.data,
			approved=True,
			prjID = str(prjID)
			)
		if comment:
			db.session.add(comment)
			db.session.commit()
			flash('Your comment has been posted.')
			return redirect(url_for('.projectProfile', prjID=proj[0].prjID) + '#top')
	comments = proj[0].comments.order_by(Comment.id.asc()).all()
	return render_template('infra/profile.html', 
							proj=proj[0], 
							cost=ast.literal_eval(proj[0].cost.encode('ascii','ignore')), 
							form=form, 
							comments=comments)


@infra.route('/profileEdit/<prjID>', methods=['GET', 'POST'])
def projectEditorProfile(prjID):
	proj = scrapedProjects.query.filter_by(prjID=prjID).all()
	form = ProjectEditorForm()
	if form.validate_on_submit():
		edit = scrapedProjects(
			prjID=proj.prjID,
			title=proj.title,
			cost=proj.cost,
			contractor=proj.contractor,
			status=form.status.data,
			srcFunds=proj.srcFunds,
			startDate=proj.startDate,
			origComp=proj.origComp,
			actComp=form.actComp.data,
			impOffice=proj.impOffice,
			latitude=form.lat.data,
			longitude=form.lon.data,
			regions=proj.regions
			)
		if edit:
			db.session.add(edit)
			db.session.commit()
			flash('Updated Project')
			return render_template('infra/editProj.html', 
						proj=proj[0], 
						cost=ast.literal_eval(proj[0].cost.encode('ascii','ignore')), 
						form=form
						)
	return render_template('infra/editProj.html', 
							proj=proj[0], 
							cost=ast.literal_eval(proj[0].cost.encode('ascii','ignore')), 
							form=form)


@infra.route('/contractors', methods=['GET', 'POST'])
def contractorList():
	numResults=0
	conID =[]
	conName =[]
	province =[]
	#print len(get_list_of_suppliers())
	listOfSuppliers = get_list_of_suppliers()
	for i in xrange(0, len(get_list_of_suppliers())):
		
		conID.append({"conID" :listOfSuppliers[i].get("org_id"),
			"conName":listOfSuppliers[i].get("org_name"),
			"province":listOfSuppliers[i].get("province")})
	return render_template('infra/contractors.html', conID=conID)



@infra.route('/contractor/<conID>', methods=['GET','POST'])
def contractorProfile(conID):
	conName = get_orginfo_from_orgid(conID)[0].get("org_name")
	conLoc = get_orginfo_from_orgid(conID)[0].get("province")
	category = get_orgcategory(conID)[0].get("businesscategory")
	bidded_projects = get_number_of_previous_bids_of_org(conID)
	total_amount_of_projects=get_awards_total_of_org(conID)[1]
	num_of_awarded = get_awards_total_of_org(conID)[0]
	return render_template('infra/conProfile.html', 
		conName=conName, 
		conLoc=conLoc,
		category=category,
		bidded_projects=bidded_projects,
		total_amount_of_projects = total_amount_of_projects,
		num_of_awarded=num_of_awarded 
		)

infraApp/templates/base.html
<html>
<head>
	<meta charset="UTF-8">
	<!--needed for the browser to fit the page to the screen-->
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0"/>
	
	<!--Leaflet CSS and BingGeocoer CSS-->
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/leaflet.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/Control.BingGeocoder.css') }}">

	<!--jQuery-->
	<script src="{{url_for('static', filename='js/jquery-2.1.1.min.js') }}"></script>
	<!--custom fonts-->
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text'/>
	<!--Bootstrap CSS-->
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.css') }}">
	<!--Custom CSS-->
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/index.css') }}">
</head>

<!--Create navigation bar-->
<body>
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
        	<div class="navbar-header">
        	      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('infra.index') }}">
                	<big>AIMS</big>
                </a>
            </div>

        	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        		<ul class="nav navbar-nav navbar-right">
				<li><a href="{{ url_for('infra.index') }}">Home</a></li>
				<li><a href="{{ url_for('infra.projectList') }}">Projects</a></li>
				<li><a href="{{ url_for('infra.contractorList') }}">Contractors</a></li>
				{% if current_user.is_authenticated() %}
					<li></li>
					<li><a href="{{ url_for('auth.logout') }}">Logout </a></li>
				{% endif %}
				{% if not current_user.is_authenticated() %}		
					<li><a href="{{ url_for('auth.login') }}">Login </a></li>
				{% endif %}
				</ul>
			</div>
		</div> 
	</nav>

{% block content %}

<!--Mapping Libraries-->
<script type=text/javascript src="{{url_for('static', filename='js/leaflet.js') }}"></script> 

<script type=text/javascript src="{{url_for('static', filename='js/Control.BingGeocoder.js') }}"></script> 

<div class="page-header">
{% for message in get_flashed_messages() %}
	<div class="alert alert-warning">
		<button type="button" class="close" data-dismiss="alert">x</button>
		{{ message }}
	</div>
{% endfor %}
	<div class = "container">
		{% block page_content %} {% endblock %}
	</div>
{% endblock %}
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
</body>
</html>