infraApp/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from flask.ext.login import UserMixin
from datetime import datetime
from . import db, login_manager
from markdown import markdown
import bleach

class Projects(db.Model):
    __tablename__ = 'projects'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    prjID = db.Column(db.String(64))
    title = db.Column(db.String(128), nullable=False)
    cost = db.Column(db.Float, nullable=False)
    funding = db.Column(db.String(16))
    contractor = db.Column(db.String(64), nullable=False, index=True)
    address = db.Column(db.Text, nullable=False)
    status = db.Column(db.Float, nullable=False)
    dateStart = db.Column(db.DateTime())
    dateEnd = db.Column(db.DateTime())
    agency = db.Column(db.String(64), nullable=False)
    lat = db.Column(db.Float)
    lon = db.Column(db.Float)
    region = db.Column(db.String(4))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), autoincrement=True)


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), nullable=False, unique=True, index=True)
    is_admin = db.Column(db.Boolean)
    password_hash = db.Column(db.String(128))
    infraProj = db.relationship('Projects', backref='implementor', lazy='dynamic') 

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')
	
    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

class scrapedProjects(db.Model):
    __tablename__ = 'dpwh'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    prjID = db.Column(db.String(64))
    title = db.Column(db.Text)
    contractor = db.Column(db.String(64))
    impOffice = db.Column(db.String(64))
    srcFunds = db.Column(db.String(64))
    cost = db.Column(db.String(64))
    status = db.Column(db.String(64))
    startDate = db.Column(db.String(64))
    origComp = db.Column(db.String(64))
    actComp = db.Column(db.String(64))
    regions = db.Column(db.String(12))
    latitude = db.Column(db.Float)
    longitude = db.Column(db.Float)
    comments= db.relationship('Comment', lazy='dynamic', backref='dpwh')

class Comment(db.Model):
    __tablename__ = "comments"
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    body = db.Column(db.Text)
    body_html = db.Column(db.Text)
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    author_name = db.Column(db.String(64))
    author_email = db.Column(db.String(64))
    approved = db.Column(db.Boolean, default=True)
    prjID = db.Column(db.String(64), db.ForeignKey('dpwh.prjID'))

    @staticmethod
    def on_changed_body(target, value, oldvalue, initiator):
        allowed_tags = [
            'a', 'abbr', 'acronym', 'b', 'blockquote', 'code',
            'em', 'i', 'li', 'ol', 'pre', 'strong', 'ul',
            'h1', 'h2', 'h3', 'p'
        ]
        target.body_html = bleach.linkify(bleach.clean(
                markdown(value, output_format='html'),
                tags=allowed_tags,strip=True
            ))

db.event.listen(Comment.body, 'set', Comment.on_changed_body)

infraApp/infra/forms.py
from flask.ext.wtf import Form
from wtforms import StringField, DateField, TextField, FloatField, SubmitField, SelectField
from wtforms.validators import Required, Length, Optional
from flask.ext.pagedown.fields import PageDownField

class AddProjectForm(Form):

    prjID = StringField('Project ID', validators=[Required(), Length(1,64)])
    title = StringField('Title of Project', validators=[Required(), Length(1,128)])
    cost = 	FloatField('Cost', validators=[Required()])
    contractor = StringField('Contractor', validators=[Required(), Length(1,64)])
    address = TextField('Address of Project', validators=[Required()])
    status = FloatField('% Completed', validators=[Required()])
    dateStart = DateField('Date Start i.e.(YYYY-MM-DD)', validators=[Required()])
    dateEnd = DateField('Date End i.e.(YYYY-MM-DD)', validators=[Required()])
    agency = StringField('Implementing Agency', validators=[Required(), Length(1,64)])
    funding = StringField('Source of Funds', validators=[Required(), Length(1,64)])
    lat = FloatField('Latitude', validators=[Required()],id='latitude')
    lon = FloatField('Longitude', validators=[Required()],id='longitude')
    region = SelectField(u'Region',
            coerce=int,
            choices=[
                (1, '01'),(2, '02'),(3, '03'),(4, '04A'),(5, '04B'),(6, '05'),(7, '06'),
                (8, '07'),(9, '08'),(10, '09'),(11, '10'),(12, '11'),(13, '12'),(13, '12'),
                (14, '13'),(15, 'CAR'),(16, 'NCR')
            ])
    submitData = SubmitField('Submit Project')

class CommentForm(Form):
    name = StringField('Name', validators=[Required(), Length(1,64)])
    email = StringField('Email', validators=[Required(), Length(1,64)])
    body = PageDownField('Comment', validators=[Required()])
    submit = SubmitField('Submit')

class SearchForm(Form):
    title = StringField('', validators=[Required()])
    submit = SubmitField('Go')

class ProjectEditorForm(Form):
    actComp = StringField('Actual Completion', validators=[Required(), Length(1,64)])
    status = FloatField('% Completed')
    lat = FloatField('Latitude:', validators=[Required(), Length(1,64)],id='latitude')
    lng = FloatField('Longitude:', validators=[Required(), Length(1,64)],id='longitude')
    submit = SubmitField('Update')

infraApp/__init__.py
from flask import Flask
from config import config
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.login import LoginManager
from flask.ext.bootstrap import Bootstrap
from flask.ext.pagedown import PageDown

login_manager = LoginManager()
login_manager.login_view = 'auth.login'

db = SQLAlchemy()

bootstrap = Bootstrap()

pagedown=PageDown()

def build_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])

    bootstrap.init_app(app)

    from infraApp.models import db
    db.init_app(app)

    from .infra import infra as infra_blueprint
    app.register_blueprint(infra_blueprint)

    login_manager.init_app(app)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    pagedown.init_app(app)

    return app

infraApp/infra/__init__.py
from flask import Blueprint
infra = Blueprint('infra', __name__)
from . import routes

infraApp/infra/routes.py
from flask import render_template, request, url_for, flash, redirect
from flask.ext.login import login_user, logout_user, login_required
from . import infra
from ..models import User, Projects, scrapedProjects, Comment
from .forms import AddProjectForm, CommentForm, SearchForm, ProjectEditorForm
from .. import db
from api_query import get_list_of_suppliers, get_orginfo_from_orgid, get_orgcategory, get_number_of_previous_bids_of_org, get_awards_total_of_org
import ast

@infra.route('/')
@infra.route('/index')
def index():
    dataList = Projects.query.order_by(Projects.dateStart.desc()).all()
    return render_template('infra/index.html', dataList=dataList)


@infra.route('/addData', methods=['GET', 'POST'])
@login_required
def addProject():
	form = AddProjectForm()
	dataList = Projects.query.order_by(Projects.dateStart.desc()).all()
	if form.validate_on_submit():
		proj = Projects(
				prjID=form.prjID.data,
				title=form.title.data,
				cost=form.cost.data,
				contractor=form.contractor.data,
				address=form.address.data,
				status=form.status.data,
				funding=form.funding.data,
				dateStart=form.dateStart.data,
				dateEnd=form.dateEnd.data,
				agency=form.agency.data,
				lat=form.lat.data,
				lon=form.lon.data,
				region=form.region.data 
			)
		db.session.add(proj)
		db.session.commit()	
		return render_template('infra/index.html', form=form, dataList=dataList)
	return render_template('infra/addData.html', form=form, dataList=dataList)

@infra.route('/projectList', methods=['GET', 'POST'])
def projectList():
	projList = scrapedProjects.query.limit(20)
	form = SearchForm()
	numResults=0
	if form.validate_on_submit():
		projList = scrapedProjects.query.filter(scrapedProjects.title.like('%'+form.title.data+'%'))
		numResults = projList.count()
		return render_template('infra/projects.html', projList=projList, form=form, numResults=numResults)
	return render_template('infra/projects.html', projList=projList, form=form, numResults=numResults)

@infra.route('/project/<prjID>', methods=['GET', 'POST'])
def projectProfile(prjID):
	proj = scrapedProjects.query.filter_by(prjID=prjID).all()
	form = CommentForm()
	comment = None
	if form.validate_on_submit():
		comment=Comment(body=form.body.data, 
			author_name = form.name.data,
			author_email = form.email.data,
			approved=True,
			prjID = str(prjID)
			)
		if comment:
			db.session.add(comment)
			db.session.commit()
			flash('Your comment has been posted.')
			return redirect(url_for('.projectProfile', prjID=proj[0].prjID) + '#top')
	comments = proj[0].comments.order_by(Comment.id.asc()).all()
	return render_template('infra/profile.html', 
							proj=proj[0], 
							cost=ast.literal_eval(proj[0].cost.encode('ascii','ignore')), 
							form=form, 
							comments=comments)


@infra.route('/profileEdit/<prjID>', methods=['GET', 'POST'])
def projectEditorProfile(prjID):
	proj = scrapedProjects.query.filter_by(prjID=prjID).all()
	form = ProjectEditorForm()
	if form.validate_on_submit():
		edit = scrapedProjects(
			prjID=proj.prjID,
			title=proj.title,
			cost=proj.cost,
			contractor=proj.contractor,
			status=form.status.data,
			srcFunds=proj.srcFunds,
			startDate=proj.startDate,
			origComp=proj.origComp,
			actComp=form.actComp.data,
			impOffice=proj.impOffice,
			latitude=form.lat.data,
			longitude=form.lon.data,
			regions=proj.regions
			)
		if edit:
			db.session.add(edit)
			db.session.commit()
			flash('Updated Project')
			return render_template('infra/editProj.html', 
						proj=proj[0], 
						cost=ast.literal_eval(proj[0].cost.encode('ascii','ignore')), 
						form=form
						)
	return render_template('infra/editProj.html', 
							proj=proj[0], 
							cost=ast.literal_eval(proj[0].cost.encode('ascii','ignore')), 
							form=form)


@infra.route('/contractors', methods=['GET', 'POST'])
def contractorList():
	numResults=0
	conID =[]
	conName =[]
	province =[]
	#print len(get_list_of_suppliers())
	listOfSuppliers = get_list_of_suppliers()
	for i in xrange(0, len(get_list_of_suppliers())):
		
		conID.append({"conID" :listOfSuppliers[i].get("org_id"),
			"conName":listOfSuppliers[i].get("org_name"),
			"province":listOfSuppliers[i].get("province")})
	return render_template('infra/contractors.html', conID=conID)



@infra.route('/contractor/<conID>', methods=['GET','POST'])
def contractorProfile(conID):
	conName = get_orginfo_from_orgid(conID)[0].get("org_name")
	conLoc = get_orginfo_from_orgid(conID)[0].get("province")
	category = get_orgcategory(conID)[0].get("businesscategory")
	bidded_projects = get_number_of_previous_bids_of_org(conID)
	total_amount_of_projects=get_awards_total_of_org(conID)[1]
	num_of_awarded = get_awards_total_of_org(conID)[0]
	return render_template('infra/conProfile.html', 
		conName=conName, 
		conLoc=conLoc,
		category=category,
		bidded_projects=bidded_projects,
		total_amount_of_projects = total_amount_of_projects,
		num_of_awarded=num_of_awarded 
		)

infraApp/templates/infra/addData.html
{% extends "base.html"%}

{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %} 

<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/leaflet.draw.css') }}">

<script type=text/javascript src="{{url_for('static', filename='js/leaflet.draw.js') }}"></script>
<script type=text/javascript src="{{url_for('static', filename='js/jquery.slimscroll.min.js') }}"></script>

<!--Handle form panel over map edit-->
  <script>
    $(function(){
      $('.panel-body').slimScroll({
          height: '100%',
          distance:'0.5%',
          color:'#022a50',
          opacity:'0.5',
          railVisible: true,
      });
    });

  </script>

  <style>
  .leaflet-draw-section{
    margin-top:5rem;
  }
  .leaflet-draw-toolbar{
    position:relative;
    top:1rem;
  }
  .leaflet-bar a {
    cursor: default;
    background-color:#022a50;
    opacity:0.7;
    color:white;
  }
  .leaflet-bar a:hover {
    cursor: default;
    background-color:#022a50;
    opacity:0.3;
    color:white;
  }
  #formContent{
    height:66%;

  }
  #map{
    width:43%;
    height:77%;
    padding: auto 3%;
    margin-top:8.5%;
  }
  .panel-footer{
    background-color:#022a50;
    opacity: 1;
  }
  .panel-default .panel-heading{
    color:white;
    background-color:#022a50 ;
    opacity: 1;
  }
  .leaflet-container {
    background: rgb(177, 211, 198);
    outline: 3;
    border-radius: 1rem;
  }
  .panel-body {
    background-color: rgba(177, 211, 198,0.15);
  }
  .leaflet-control-geocoder{
    margin-top: 10%;
    position:absolute;
    top:5rem;
    right:.5rem;
  }
  .leaflet-control-geocoder-form{
    margin:0 auto;
  }
  .leaflet-control-geocoder-input{
    border-radius: 0.5rem;
    border-color:#022a50;
    border-width: 0.15rem;
    width:45rem;
    height:5%;
  }
  .leaflet-control-geocoder-button{
    display:inline;
    background-color:#022a50;
    color:white;
    border-radius: 0.5rem;
    border-color:  transparent;
    margin-left:0.5rem;
  }
  .leaflet-control-geocoder-expanded{
    position:absolute;
    top:50rem;
    padding: 0 auto;
    width:52rem;
  }
  .leaflet-top .leaflet-control {
    position: absolute;
    top:1rem; 
  }
  #content{
    margin-top: 8rem;
    height:100%;
  }
  html{
    overflow:hidden;
  }
  body { 
    background: url('../../static/img/login.jpg') no-repeat center center fixed; 
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
  }

  .panel-default {
    opacity: 0.9;
  }
  </style>
</style>

<!--Setup map editor-->
<div class="container" id="content">
<div class="col-lg-6 pull-left" id="map">
<script type=text/javascript src="{{url_for('static', filename='js/mapEdit.js') }}"></script>
<!--Load data in DB-->
<script>
{% for data in dataList %}
var marker = L.marker( [{{ data.lat }},{{ data.lon }}]).addTo(map)

marker.bindPopup(
  "ID: {{data.prjID}} <br>"+ 
  "Project name: {{data.title}} <br>"+
  "Cost: {{data.cost}} <br>"+
  "Contractor: {{data.contractor}} <br>"+
  "Start Date: {{data.dateStart}} <br>"+
  "End Date: {{data.dateEnd}} <br>"+
  "% Completed: {{data.status}} <br>"
  );

{% endfor %}
</script>
</div>

<div class="col-lg-6 pull-right" id="formContent">
  <div class="panel panel-default">
    <div class="panel-heading">
      <strong>Project Information</strong>
    </div>
        
  <div class="panel-body">
      {{ wtf.quick_form(form) }}
  </div>
  <div class="panel-footer"><a href="#" class=""></a></div>
</div>
</div>
</div>
{% endblock %}

infraApp/templates/infra/conProfile.html
{% extends "base.html"%}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}

<style>
#container{
	padding-top:50px;

}
.col-md-8 {
    text-align: justify;
    text-justify: inter-word;
}
#map{
	height:250px;

}
#conInfo{
	padding-left:5rem;
}
</style>

<div id="container">
    <h2>Contractor Profile</h2>
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-12">
            <div class="well well-sm">
                <div class="row">
                    <div class="col-sm-6 col-md-4">
                    	<div id="map">
                    	<script>
							var map = L.map('map').setView([12.9966338,122.2119], 4);
							L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
							    attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
							}).addTo(map);
							</script>
                    	</div>
                    </div>
                    <div class="col-sm-6 col-md-8" id="conInfo">
                        <h4>Contractor</h4>
                        <b>Name:</b> {{conName}}
                        <br />
                        <b>Location: </b><small>{{conLoc}}</small>
                        <br />
                        <b>Category:</b>{{category}}
                        <br />
                        <b>Number of Bidded Projects: </b>{{bidded_projects}}
                        <br />
                        <b>Number of Awarded Projects: </b>{{num_of_awarded}}
                        <br />
                        <b>Total Amount of Projects: </b>PHP {{total_amount_of_projects}}
                        <br />
                        <b>Other Projects: </b>
                        <br />
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

infraApp/templates/infra/contractors.html
{% extends "base.html"%}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}
<style>
#table-responsive{
	padding-top:3%;}
body{padding-top:10px;}

.glyphicon {  margin-bottom: 10px;margin-right: 10px;}

small {
display: block;
line-height: 1.428571429;
color: #999;
	}

#conName, #conID, #regionsData{
	text-justify: inter-word;
	text-align: center;
}
th{
	text-justify: inter-word;
	text-align: center;
}
</style>

<div id="table-responsive">
<table class="table table-striped">
   <thead>
   		<tr>
   			<div class="pull-left"> 
			<br>
			</div>
   		</tr>
      	<tr id="heading">
	        <th>Contractor ID</th>
	        <th>Contractor Name </th>
	        <th>Region</th>
      	</tr>
   </thead>
   <tbody>
   {% for conID in conID%}
   		<tr>
 	
			<td id="conID"> {{conID.conID}} </td>
			<td id="conName">
			  		<a href="{{ url_for('infra.contractorProfile', conID=conID.conID ) }}">
					<small>{{conID.conName}}</small>
					</a>
				
			</td>
			<td id="regionsData"> {{conID.province}}</td>

			{% endfor %}
		</tr>
   </tbody>
</table>

</div>

{% endblock %}

infraApp/templates/infra/index.html
{% extends "base.html"%}

{% block page_content %}
<!--Load gis layers-->
<script src="{{url_for('static', filename='js/regions.js') }}"></script>
<script src="{{url_for('static', filename='js/provinces.js') }}"></script>
<script src="{{url_for('static', filename='js/airports.js') }}"></script>
<script src="{{url_for('static', filename='js/indusZone.js') }}"></script>
<script src="{{url_for('static', filename='js/roads.js') }}"></script>
<script src="{{url_for('static', filename='js/seaports.js') }}"></script>
<script src="{{url_for('static', filename='js/newTwo.js') }}"></script>
<script src="{{url_for('static', filename='js/leaflet-categorized-layers.min.js') }}"></script>

<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/leaflet-categorized-layers.min.css') }}" />
<script src="{{url_for('static', filename='js/leaflet.markercluster-src.js') }}"></script>
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/MarkerCluster.Default.css') }}" />
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/MarkerCluster.css') }}" />
	<style>
	#region, #provinces, #industrial, #roads {
		position:absolute;
		height:7rem;
		width:22rem;
    	padding: 6px 8px;
    	font: 14px/16px Arial, Helvetica, sans-serif;
    	background: white;
    	background: rgba(255,255,255,0.8);
    	box-shadow: 0 0 15px rgba(0,0,0,0.2);
    	border-radius: 5px;
    	left:5rem;
    	top:5rem;
    	z-index:1002;
	}

	.pop{
		height:7rem;
		width:22rem;
    	font: 14px/16px Arial, Helvetica, sans-serif;
    	background: white;
    	background: rgba(255,255,255,0.8);
    	box-shadow: 0 0 15px rgba(0,0,0,0.2);
    	border-radius: 5px;
	}

	.content{
		padding-top:10px;
		background: transparent;
		margin:0 auto;
	}

	.content h5{
		font-size:14px;
    	margin: 0 0 5px;
    	color: #B21480;
	}

	#provinces, #industrial{
		line-height: 12px;
		left:28rem;
		height:8rem;
	}

	#industrial{
		line-height: 5px;
		width:32rem;
		top:15rem;
		left:25rem;
	}

	#region h4, #provinces h4{
		font-size:18px;
    	margin: 0 0 5px;
    	color: #3682B6;
	}
	.leaflet-control-layers{
		top:5rem;
		right:3rem;
		z-index:5;
	}
	</style>

<div class="container">
	<div class="fill">
		<div id ="map">
				<script src="{{url_for('static', filename='js/map.js') }}"></script>
				<script>
					{% for data in dataList %}
						var marker = L.marker( [{{ data.lat }},{{ data.lon }}]).addTo(map)
						marker.bindPopup("Project name: {{data.title}}" );
					{% endfor %}
				</script>
		</div>
	</div>
</div>
{% endblock %}

infraApp/templates/infra/profile.html
{% extends "base.html"%}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}


<style>
#container{
	padding-top:40px;

}
.col-md-8 {
    text-align: justify;
    text-justify: inter-word;
}
#map{
	height:250px;

}
#projInfo{
	padding-left:5rem;
}
#headerProject{

}
</style>
<script type=text/javascript src="{{url_for('static', filename='js/d3.min.js') }}"></script> 
<div id="container">

    <span id="headerProject">Project Profile</span>
    {% if current_user.is_authenticated() %}
        <span class="pull-right">
            <a href="{{ url_for('infra.projectEditorProfile', prjID = proj.prjID ) }}">Edit Project</a>
        </span>
    {% endif %}
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-12">
            <div class="well well-sm">
                <div class="row">
                    <div class="col-sm-6 col-md-4">
                    	<div id="map">

                    	<script>
							var map = L.map('map').setView([12.9966338,122.2119], 4);
							L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
							    attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
							}).addTo(map);
							function statusUpdate(){
									var stat = {{ proj.status | safe}}
									var update = "terminated"; 
									if( stat == 0){
										update = "not yet started";
									}
									else if (stat > 0 && stat <100 ){
										update="ongoing";
									}else{
										update="complete";
									}
									return update;
								}
                    	</script>
                    	</div>
                    </div>
                    <div class="col-sm-6 col-md-8" id="projInfo">
                        <h4>{{proj.prjID}}</h4>
                        <b>Title | Location: </b><small>{{ proj.title }}</small>
                        <p>
                            <b>Region:</b> {{ proj.regions }}
                            <br />
                            <b>Contractor:</b> {{ proj.contractor }}
                            <br />
                            <b>Implementing Office:</b>{{ proj.impOffice }}
                            <br />
                            <b>Source of Funds:</b>{{ proj.srcFunds }}
                            <br />
                            <b>Cost(x1000):</b>{{ cost | safe}}
                            <br />
                            <b>Start Date:</b>{{ proj.startDate }}
                            <br />
                            <b>Target Date:</b>{{ proj.origComp }}
                            <br />
                            <b>Actual Finish:</b>{{ proj.actComp }}
                            <br />
                            <b>Status:</b><span id="output"></span>
                            <script>
									var stat = {{ proj.status | safe}}
									var update = "bato"; 
									if( stat == 0){
										update = "not yet started";
									}
									else if (stat > 0 && stat <100 ){
										update="ongoing";
									}else{
										update="complete";
									}
									$('#output').html(update);
							</script>                         
                        </p>
                        <center><div id="chart">{{proj.status | safe}}% Completed</div></center>

                    </div>
                </div>
            </div>
        </div>
    </div>

{% if comments %}
	<h3>Comments</h3>
	{% for comment in comments %}
		{% set index = loop.index %}
			<p>
				<span class="label label-default">#{{ index }} </span>
				<b> {{ comment.author_name }}</b>
			</p>
			<div class="comment-body">
				{{comment.body_html | safe}}
			</div>	
	{% endfor %}
{% endif %}

<h3 id="comment-form"> Write a Feedback </h3>
{{wtf.quick_form(form, action='#comment-form')}}

</div>

{{ super() }}
{{ pagedown.include_pagedown() }}

<script>
    var w = 200;
    var h = 200;
    var r = h/2;
    var color = d3.scale.category20c();

    var data = [{"label":"", "value":{{proj.status | safe}}}, 
    		          {"label":"", "value":100 - {{proj.status|safe}}}];


    var vis = d3.select('#chart').append("svg:svg").data([data]).attr("width", w).attr("height", h).append("svg:g").attr("transform", "translate(" + r + "," + r + ")");
    var pie = d3.layout.pie().value(function(d){return d.value;});

    // declare an arc generator function
    var arc = d3.svg.arc().outerRadius(r);

    // select paths, use arc generator to draw
    var arcs = vis.selectAll("g.slice").data(pie).enter().append("svg:g").attr("class", "slice");
    arcs.append("svg:path")
        .attr("fill", function(d, i){
        	if(i==0){
        		return color(i)
        	}else{
        		return "rgba(225,225,225,0.5)"
        	}
        })
        .attr("d", function (d) {
            return arc(d);
        });

    // add the text
    arcs.append("svg:text").attr("transform", function(d){
    			d.innerRadius = 0;
    			d.outerRadius = r;
        return "translate(" + arc.centroid(d) + ")";}).attr("text-anchor", "middle").text( function(d, i) {
        return data[i].label;}
    		);
</script>


{% endblock %}

infraApp/templates/infra/projects.html
{% extends "base.html"%}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}
<style>
#table-responsive{
	padding-top:3%;}
body{padding-top:10px;}

.glyphicon {  margin-bottom: 10px;margin-right: 10px;}

small {
display: block;
line-height: 1.428571429;
color: #999;
	}

#projTitle{
	text-justify: inter-word;
	text-align: justify;
}

#regionsData{
	text-justify: inter-word;
	text-align: center;
}

th{
	text-justify: inter-word;
	text-align: center;
}
</style>

<div id="table-responsive">
<table class="table table-striped">
   <thead>
   		<tr>
   			<div class="pull-left col-lg-12">
	   		<form method="post" class="form-group" role="form">
	   			<label class="control-label pull-left" for="title">Search </label>
		   		{{ form.csrf_token }}
		   		<input class="input-medium search-query" id="title" name="title" required type="text" value="">
				<span class="numResults">
					&nbsp;&nbsp;Returned {{ numResults }} results
				</span>
				{% if current_user.is_authenticated() %}
						<a class="pull-right" href="{{ url_for('infra.addProject') }}">Add Project</a>
					{% endif %}

			</form>
			<br>
			</div>
   		</tr>
      	<tr id="heading">
	        <th>Project ID</th>
	        <th>Project Name | Location</th>
	        <th>Region</th>
      	</tr>
   </thead>
   <tbody>
   	{% for proj in projList %}
		<tr>
			<td> {{ proj.prjID | safe }}</td>
			<td id="projTitle"><a href="{{ url_for('infra.projectProfile', prjID=proj.prjID ) }}"><small>{{ proj.title | safe }}</small> </a></td>
			<td id="regionsData"> {{ proj.regions | safe }}</td>
		</tr>
	{% endfor %}
   </tbody>
</table>

</div>

{% endblock %}